# Data paths 
train_datasets: ['sun_train', 'transp_train']
dev_datasets: ['sun_val', 'transp_val']
test_datasets: ['sun_val', 'transp_val']
predict_datasets: []

# Model parameters
image_h: 320
image_w: 320
backbone: two_headed_resnet

num_categories: 2

categories_sun: [
  other,
  floor,
]

categories_trans: [
  other,
  glass,
]

cat_mapping_trans: {
  'background': 'other', 
  'shelf': 'glass',
  'jar or tank': 'glass',
  'freezer': 'glass',
  'window': 'glass',
  'glass door': 'glass', 
  'eyeglass': 'glass', 
  'cup': 'glass', 
  'floor glass': 'glass', 
  'glass bowl': 'glass',
  'water bottle': 'glass', 
  'storage box': 'glass',
}

cat_mapping_sun: {
  'wall': 'other',
  'floor': 'floor',
  'cabinet': 'other',
  'bed': 'other',
  'chair': 'other',
  'sofa': 'other',
  'table': 'other',
  'door': 'other',
  'window': 'other',
  'bookshelf': 'other',
  'picture': 'other',
  'counter': 'other',
  'blinds': 'other',
  'desk': 'other',
  'shelves': 'other',
  'curtain': 'other',
  'dresser': 'other',
  'pillow': 'other',
  'mirror': 'other',
  'floor_mat': 'other',
  'clothes': 'other',
  'ceiling': 'other',
  'books': 'other',
  'fridge': 'other',
  'tv': 'other',
  'paper': 'other',
  'towel': 'other',
  'shower_curtain': 'other',
  'box': 'other',
  'whiteboard': 'other',
  'person': 'other',
  'night_stand': 'other',
  'toilet': 'other',
  'sink': 'other',
  'lamp': 'other',
  'bathtub': 'other',
  'bag': 'other',
}

dataset2task: {
  'train': {
    'sun_train': 0,
    'transp_train': 1,
  },
  'valid': {
    'sun_val': 0,
    'transp_val': 1,
  },
  'test': {
    'sun_val': 0,
    'transp_val': 1,
  }
}

# Training parameters
max_epochs: 10
# Number of images from one dataset in batch
batch_size: 5
learning_rate: 0.00005
random_seed: 42
log_plot_freq: 5
